apiVersion: v1
kind: Service
metadata:
  name: animal-classifier-service
spec:
  type: NodePort
  selector:
    app: animal-classifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # This is the port you will use on your machine